### ISSUE TITLE
Error getting a feature report from the device

### ISSUE THREAD

**Issue by ghost** [rene-aguirre/pywinusb#15]
I am facing a little bit of difficulty in obtaining feature reports from the device, I am facing this error that seems to suggest that the error is because the data passed on from the device cannot be set into a value array that is used by the library. Do you know of a way I can get around this issue?
'''
Traceback (most recent call last):
    print reports[1].get_raw_data()
  File "C:\APython27\lib\site-packages\pywinusb\hid\core.py", line 1425, in get_raw_data
    self.__prepare_raw_data()
  File "C:\APython27\lib\site-packages\pywinusb\hid\core.py", line 1416, in __prepare_raw_data
    len(self.__raw_data)) )
  File "C:\APython27\lib\site-packages\pywinusb\hid\winapi.py", line 382, in __init__
    raise helpers.HIDError("hidP error: %s" % self.error_message_dict[error_code])
pywinusb.hid.helpers.HIDError: hidP error: not value array
'''

**Comment by rene-aguirre** [comment]
I can't reproduce this issue.
